import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

const MainLayout = ({ children }: { children: React.ReactNode }) => (
	<html className={inter.className} lang="en">
		<body>{children}</body>
	</html>
);

export default MainLayout;
