import { Inter } from "next/font/google";

import "~/app/global.css";
import { css } from "~/styled-system/css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

const MainLayout = ({ children }: { children: React.ReactNode }) => (
	<html className={inter.variable} lang="en">
		<body
			className={css({
				fontFamily: "body",
			})}
		>
			{children}
		</body>
	</html>
);

export default MainLayout;
